/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export default class Constants {
  // grid useSizeType
  public static GUTTER = 0;
  public static XS_COLUMNS = 2;
  public static XS_SPAN = 2;
  public static XS_OFFSET = 0;
  public static SM_COLUMNS = 4;
  public static SM_SPAN = 4;
  public static SM_OFFSET = 0;
  public static MD_COLUMNS = 8;
  public static MD_SPAN = 8;
  public static MD_OFFSET = 0;
  public static LG_COLUMNS = 12;
  public static LG_SPAN = 8;
  public static LG_OFFSET = 2;

  public static DIALOG_GUTTER = 16;
  public static DIALOG_MARGIN = 16;
  public static DIALOG_MARGIN_VERTICAL = 12;
  public static DIALOG_MD_SPAN = 4;
  public static DIALOG_MD_OFFSET = 2;
  public static DIALOG_LG_SPAN = 4;
  public static DIALOG_LG_OFFSET = 4;

  // 100% width,height
  public static FULL_WIDTH = '100%';
  public static FULL_HEIGHT = '100%';

  // public property style
  public static PERMISSION = 1;
  public static APPLICATION = 0;
  public static LAYOUT_WEIGHT = 1;
  public static FLEX_GROW = 1;
  public static TEXT_BIG_FONT_SIZE = 20;
  public static TEXT_MIDDLE_FONT_SIZE = 16;
  public static TEXT_SMALL_FONT_SIZE = 14;
  public static TEXT_SMALLER_FONT_SIZE = 12;
  public static TEXT_LINE_HEIGHT = 22;
  public static TEXT_BIG_LINE_HEIGHT = 28;
  public static TEXT_SMALL_LINE_HEIGHT = 19;
  public static CONSTRAINTSIZE_MINHEIGHT = 48;
  public static LISTITEM_ROW_HEIGHT = 48;
  public static LISTITEM_PADDING_LEFT = 24;
  public static LIST_PADDING_LEFT = 12
  public static LISTITEM_PADDING_RIGHT = 24;
  public static LISTITEM_PADDING_LEFT_RECORD = 32;
  public static LISTITEM_PADDING_RIGHT_RECORD = 50;
  public static LISTITEM_MARGIN_BOTTOM = 12;
  public static LISTITEM_HEIGHT_PERMISSION = 64;
  public static LISTITEM_HEIGHT_APPLICATION = 72;
  public static IMAGE_HEIGHT = 24;
  public static IMAGE_WIDTH = 12;
  public static IMAGE_HEIGHT_RECORD = 12;
  public static IMAGE_WIDTH_RECORD = 24;
  public static IMAGE_HEIGHT_RECORD_APPLICATION = 16;
  public static IMAGE_WIDTH_RECORD_APPLICATION = 16;
  public static TITLE_MARGIN_BOTTOM = 16;
  public static SUBTITLE_MIN_HEIGHT = 48;
  public static SUBTITLE_LINE_HEIGHT = 24;
  public static SUBTITLE_PADDING_TOP = 16;
  public static SUBTITLE_PADDING_BOTTOM = 8;
  public static TAB_HEIGHT = 56;
  public static TAB_LINE_HEIGHT = 100;
  public static TAB_INNER_PADDING = 8;
  public static TAB_DECORATION_HEIGHT = 2;
  public static TAB_DECORATION_POSITION_Y = 6;
  public static DEFAULT_PADDING_START = 12;
  public static DEFAULT_PADDING_END = 12;
  public static DEFAULT_PADDING_TOP = 12;
  public static DEFAULT_PADDING_BOTTOM = 12;
  public static DEFAULT_MARGIN_START = 12;
  public static DEFAULT_MARGIN_END = 12;
  public static DEFAULT_MARGIN_TOP = 12;
  public static DEFAULT_MARGIN_BOTTOM = 12;
  public static DEFAULT_SLIDER_WIDTH = 60;
  public static DEFAULT_SLIDER_HEIGHT = 40;
  public static OFFSET = 100;
  public static CLICK_SHADOW_LENGTH = 48;
  public static DIVIDER = '1px';
  public static DIVIDER_HEIGHT = 24;
  public static DIVIDER_WIDTH = '2px';
  public static DIVIDER_WIDTH_THIN = '1px';
  public static DIVIDER_WIDTH_NUM = 2;
  public static DIVIDER_MARGIN_RIGHT_PERMISSION = 52;
  public static DIVIDER_MARGIN_RIGHT_APPLICATION = 68;
  public static START_SUBSCRIPT = 0;
  public static END_SUBSCRIPT = 500;
  public static MAXIMUM_HEADER_LINES = 1;
  public static MAXIMUM_HEADER_WIDTH = 200;
  public static MAXIMUM_HEADER_HEIGHT = 500;
  public static MAXIMUM_HEADER_LENGTH = 1000;
  public static RECORD_PADDING_BOTTOM = '20%';

  // icon of dialog
  public static DIALOG_ICON_WIDTH = 32;
  public static DIALOG_ICON_HEIGHT = 32;
  public static DIALOG_ICON_MARGIN_TOP = 24;

  // label text of dialog
  public static DIALOG_LABEL_FONT_SIZE = 10;
  public static DIALOG_LABEL_MARGIN_TOP = 2;
  public static DIALOG_LABEL_LINE_HEIGHT = 14;

  // request text of dialog
  public static DIALOG_REQ_FONT_SIZE = 20;
  public static DIALOG_REQ_MARGIN_TOP = 16;
  public static DIALOG_REQ_MARGIN_BUTTOM = 16;
  public static DIALOG_REQ_MARGIN_LEFT = 24;
  public static DIALOG_REQ_MARGIN_RIGHT = 24;
  public static DIALOG_REQ_LINE_HEIGHT = 24;

  // description text of dialog
  public static DIALOG_DESP_FONT_SIZE = 16;
  public static DIALOG_DESP_MARGIN_TOP = 0;
  public static DIALOG_DESP_MARGIN_LEFT = 24;
  public static DIALOG_DESP_MARGIN_RIGHT = 24;
  public static DIALOG_DESP_MARGIN_BOTTOM = 8;
  public static DIALOG_DESP_LINE_HEIGHT = 21;

  public static BUTTON_MARGIN_TOP = 8;
  public static BUTTON_MARGIN_LEFT = 16;
  public static BUTTON_MARGIN_RIGHT = 16;
  public static BUTTON_HEIGHT = 40;
  public static BUTTON_LEFT = 8;
  public static BUTTON_RIGHT = 8;

  public static DIALOG_PRIVACY_BORDER_RADIUS = 32;
  public static DIALOG_PADDING_BOTTOM = 16;
  public static DIALOG_PADDING_BOTTOM_LOW = 8;
  public static MARGIN_ZERO = 0;
  public static BUTTON_MARGIN_ROW = 4;

  public static TITLE_MIN_FONT_SIZE = 16;
  public static CROSS_LINE_RATIO = 0.2;
  public static CROSS_LINE_RESIZE_PARAM = 1.25;

  public static FONT_SCALE_DEFAULT = 1;
  public static FONT_SCALE_MAX = 1.8;
  public static MAX_DIALOG_WIDTH = 400;

  //pc
  public static PC_ICON_MARGIN_TOP = 24;

  public static PC_TITLE_MARGIN_TOP = 16;
  public static PC_TITLE_MARGIN_SIDE = 24;

  public static PC_CONTENT_MARGIN_TOP = 16;
  public static PC_CONTENT_MARGIN_SIDE = 24;

  public static PC_OPERATE_MARGIN_SIDE = 16;
  public static PC_OPERATE_MARGIN_TOP = 16;
  public static PC_OPERATE_MARGIN_BUTTOM = 16;

  public static PC_DIALOG_WIDTH = 400;
  public static PC_BUTTON_HEIGHT = 40;

  public static PC_RDIUS_16 = 16;
  public static PC_RDIUS_12 = 12;
  public static PC_RDIUS_8 = 8;
  public static PC_DOCK_HEIGHT = 120;
  public static PC_INIT_CONTENT_HEIGHT = 230;
  public static PC_BUTTON_MARGIN_ROW = 8;

  public static PC_OUTLINE_COLOR = '#20FFFFFF'; 
  
  //  tv param config
  public static TV_BUTTON_FONT_SIZE = 18;
  public static TV_BUTTON_HEIGHT = 40;
  public static TV_RADIUS_20 = 20;
  public static TV_RADIUS_16 = 16;
  public static TV_DIALOG_ICON_WIDTH = 48;
  public static TV_ICON_MARGIN_TOP = 24;
  public static TV_LABEL_FONT_SIZE = 20;
  public static TV_TITLE_MARGIN_SIDE = 24;
  public static TV_CONTENT_FONT_SIZE = 16;

  public static TAG = 'BgTaskDialog_Service ';


  // continuous task mode
  public static SUBMODE_MEDIA_PROCESS_NORMAL_NOTIFICATION = 9;
  public static SUBMODE_VIDEO_BROADCAST_NORMAL_NOTIFICATION = 10;
  public static SUBMODE_WORK_OUT_NORMAL_NOTIFICATION = 11;

  // authType
  public static AUTH_DENIED = 2;
  public static AUTH_GRANTED_ONCE = 3;
  public static AUTH_GRANTED_ALWAYS = 4;
}